### ISSUE TITLE
Feature Request: Anti-Keystroke Fingerprinting Tool

### ISSUE THREAD

**Issue by HulaHoopWhonix** [subgraph/subgraph-os-issues#103]
Keystroke fingerprinting works by measuring how long keys are pressed and the time between presses. Its very high accuracy poses a serious threat to anonymous users.[1]

This tracking technology has been deployed by major advertisers (Google, Facebook), banks and massive online courses. Its also happening at a massive scale because just using an interactive JS application in presence of a network adversary that records all traffic allows them to construct biometric models for virtually everyone (think Google suggestions) even if the website does not record these biometric stats itself.[2] They have this data from everyone's clearnet browsing and by comparing this to data exiting the Tor network they will unmask users.

As a countermeasure security researcher Paul Moore created a prototype Chrome plugin known as KeyboardPrivacy. It works by caching keystrokes and introducing a random delay before passing them on to a webpage.[3] Unfortunately there is no source code available for the add-on and the planned Firefox version has not surfaced so far. There are hints that the author wants to create a closed hardware soltuion that implements this which does not help our cause.

A very much needed project would be to write a program that mimics the functionality of the this add-on but on the display server / OS level. Ideally the solution would be compatible with Wayland for the upcoming transition in the near future.

[1] http://arstechnica.com/security/2015/07/how-the-way-you-type-can-shatter-anonymity-even-on-tor/

[2] http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=7358795

[3] https://archive.is/vCvWb

**Comment by xSmurf** [comment]
This is really a TorBrowser issue rather than an issue to be fixed at the OS level.

As such this is already being addressed:

https://trac.torproject.org/projects/tor/ticket/3059

https://trac.torproject.org/projects/tor/ticket/1517

**Comment by adrelanos** [comment]
Unfortunately not yet fixed in Tor Browser.

[Quote](https://www.lightbluetouchpaper.org/2015/07/30/double-bill-password-hashing-competition-keyboardprivacy/#comment-1288166) Dr. Steven Murdoch, Researcher and Developer

> Tor Browser does reduce the precision of the Javascript timers available for fingerprinting, but Runa’s experiment shows that this is not sufficient to defeat the attack.

-----

It's very useful to have it fixed on the OS level. If it was fixed on the host, then even compromised VMs could not perform keystroke fingerprinting. Another reason is, that other applications (chat clients come to mind) and others that implement javascript one or another way, may be leaking this also. So having this fixed in Tor Browser is nice but non-ideal.
