### ISSUE TITLE
Tor Browser wont start

### ISSUE THREAD

**Issue by mydayyyy** [subgraph/subgraph-os-issues#113]
Hi,

I install the Tor Browser but after that nothing happens. Same result after update and reinstall. 
When will this Problem solve?

mydayyyy

**Comment by 0x6A6F7368** [comment]
They probably can't help you if you don't investigate logfiles (it's an alpha release). Please verify /var/log/syslog and copy-paste result here.

I assume you're "stuck" in same situation than me.
If so, you probably have something like this in your logfiles:


> - Mar 23 01:34:05 subgraph kernel: [  665.842249] PAX: execution attempt in: <anonymous mapping>, 323fc950000-323fc960000 323fc950000
- Mar 23 01:34:05 subgraph kernel: [  665.842255] PAX: terminating task: **/home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_fr/Browser/firefox**(firefox):2731, uid/euid: 1000/1000, PC: 00000323fc9506e0, SP: 000003942c471628
- Mar 23 01:34:05 subgraph kernel: [  665.842258] PAX: bytes at PC: 55 48 8b ec 53 41 54 41 55 41 56 41 57 ff 75 18 4c 8b f4 4c 
- Mar 23 01:34:05 subgraph kernel: [  665.842267] PAX: bytes at SP-8: 0000000e00000420 00000324066c9e28 00000000000008bf 000003942c471798 0000000000000001 00000000000002ff 0000032408856990 00000323efc03400 000003942c472180 0000000000000000 0000000000000000 

To solve (not really, it's probably less secure) this problem, you have to disable pax protection for memory mapping (MPROTECT).
Try: **setfattr -n user.pax.flags -v "m" PROGRAM_PATH** with PROGRAM_PATH refer to the path of firefox on your system. 
Here: /home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_fr/Browser/firefox

Also, you can use the paxrat tool configuration file. 
See https://github.com/subgraph/paxrat
You can find reference for various paxflags in man paxctl. (DON'T USE paxctl tool for set ELF header flags).


If your problem is a different one, just ignore this message. 
That avoid me from opening a new issue.

But... why firefox (tor browser) have to map memory with PROT_EXEC flag ?

**Comment by xSmurf** [comment]
As pointed out by @0x6A6F7368 this is most likely due to the ionotify hook in paxrat not setting the pax flag on the torbrowser. It is a known issue ( #54 ) which can be solved by running `sudo paxrat -c /etc/paxrat/paxrat_tbl.conf` inside a terminal after the TBB installation has completed as described in the caveats notes. This issue will go away completely once TBB is properly packaged ( #18 ).

If this fix doesn't work please come back, ideally with a copy of the `/var/lib/oz-daemon.log` and `dmesg`.

**Comment by willscott** [comment]
A related issue I've run into is that there's a sometimes a broken oz container left over that torbrowser won't start up happily within:
```
Mar 23 06:23:40 subgraph oz-daemon[810]: 2016/03/23 06:23:40 Launch message received. Path: /usr/bin/torbrowser-launcher Name:  Pwd: /home/user Args: []
Mar 23 06:23:40 subgraph oz-daemon[810]: 2016/03/23 06:23:40 Found running sandbox for `torbrowser-launcher`, running program there
Mar 23 06:23:40 subgraph oz-daemon[810]: 2016/03/23 06:23:40 run program command failed: dial unix /srv/oz/sockets/oz-init-control-c8b7a106ac324729: connect: no such file or directory
Mar 23 06:23:40 subgraph torbrowser.desktop[1932]: ok received
```

**Comment by xSmurf** [comment]
No more information from requester, I'm closing this ticket.

@willscott what you are describing is a different but known problem. I opened a ticket for this particular issue: https://github.com/subgraph/oz/issues/55
