### ISSUE TITLE
Repo is insufficiently signed?

### ISSUE THREAD

**Issue by pietrearby** [subgraph/subgraph-os-issues#114]
![nsffsrp](https://cloud.githubusercontent.com/assets/17863703/13986793/9c7862a6-f104-11e5-9fa9-a1ea2e94d8bc.png)

**Comment by xSmurf** [comment]
Some changes were syncing to the repo this morning, is it possible that you hit update right at that very moment? ie: does this happen consistently or just this once?

**Comment by pietrearby** [comment]
It happens every time since this morning. I ran it multiple times, the last time a few seconds ago.

**Comment by pietrearby** [comment]
Confirmed on another installation. It happens after last dist-upgrade. All it takes is to run apt-get update after that.

**Comment by xSmurf** [comment]
As an update this is following a recent apt-get upgrade which deprecated SHA1 (a good thing) and show be fixed soon.

**Comment by pietrearby** [comment]
Good news.

**Comment by pietrearby** [comment]
@xSmurf and what about recent _Hash sum mismatch_ on _aaron/main amd64_? The same reason?

**Comment by xSmurf** [comment]
No this just happens sometimes when you catch a repo while it's syncing, try a new circuit.

**Comment by pietrearby** [comment]
10 out of 10 circuits throw error.

**Comment by xSmurf** [comment]
@pietrearby is there a chance you could switch `tor+http(s)` to just `http(s)` and see if that persist? Also, is this on the main Debian repositories or our?

**Comment by pietrearby** [comment]
@xSmurf  it's our _aaron/main_. I switched to `https` as you suggested and it went smoothly. Then I switched back to `tor+https` and everything seems fine.

**Comment by mckinney-subgraph** [comment]
There is now a subgraph-archive-keyring with a new release signing key, instead of using my old personal GPG key to sign everything. We will give everyone a week or two to migrate to this key before signing the release with it.

It can be installed manually via:
```
$ sudo apt-get install subgraph-archive-keyring
``` 

Or just by upgrading the subgraph-standard metapackage.

The git repo for the package is here:
https://github.com/subgraph/subgraph-archive-keyring

Also, the repo is insufficiently signed message should go away on the next `apt-get update` signed it is resigned with the original key but different defaults. Please let me know if this is not the case. Thanks!

**Comment by mckinney-subgraph** [comment]
Our repo is now signed with the new release signing key.

Instructions on how to manually install the key (if you missed grabbing it via subgraph-archive-keyring) can be found here:
https://subgraph.com/sgos/download/index.en.html
