### ISSUE TITLE
Consider locales-all instead of locales.

### ISSUE THREAD

**Issue by xSmurf** [subgraph/subgraph-os-issues#124]
This one was sent to us by email from Tengu:

> Following a small chat with @xSmurf on the IRC, here's a small report
regarding the "locale" management on SGOS.
> 
> Currently, we have to chose, when we install the OS, what locales we
actually want. Default Debian stuff, for sure.
> 
> The idea would be to install locales-all instead of locales.
> 
> locales-all contains all the pre-compiled locales in a single package.
> This allows many thing, among them:
> - change the locales in gnome's setting "region and language" without having to launch dpkg-recondigure locales
> - maybe drop an installation step/dialog
> 
> That would require a thing like that in the preseed:
> d-i preseed/late_command string apt-install locales-all
> 
> Also, if the dialog is dropped, this would mean SGOS will enforce a locale during installation - this might be a bad idea for the "target users"
> 
> Anyways, I think adding locales-all at the end would be a good idea, even if the "select locales" dialog at install time is kept.

**Comment by mckinney-subgraph** [comment]
Added locales-all:
https://github.com/subgraph/subgraph_desktop_stretch/commit/91eb40e904d67af110cf66b2fc5720f85b626f4b

I am not sure of the value of changing the locale handling in debian-installer. We will also be moving away from it at some point so that may be a time to revisit locale handling during the install.
