### ISSUE TITLE
Debian stretch repos commented out after March 30 ISO install

### ISSUE THREAD

**Issue by dma** [subgraph/subgraph-os-issues#137]
Debian package repos for stretch (incl security updates) were commented out in sources.list after the install. Reason cited in sources.list was failure to verify.

**Comment by mckinney-subgraph** [comment]
The issue seems to be that debian-installer has problems verifying repos with a tor apt-transport (the problem occurs in the apt-setup geneators). As the tor transport was also causing other problems (and Subgraph OS automatically routes apt-get over Tor without the transport), it has been removed.

Fixed in:
https://github.com/subgraph/subgraph_desktop_stretch/commit/e499806f67154492ccb28127c9958a5b1ef6353d
