### ISSUE TITLE
powertop and tlp do not work with subgraphos kernel 

### ISSUE THREAD

**Issue by ghost** [subgraph/subgraph-os-issues#199]
The following packages do not appear to work with subgraphos it seems they conflict with the subgraphos kernel. 

thinkfan tp-smapi-dkms acpi-call-dkms tlp tlp-rdw powertop

This is problematic for those on older hardware as these packages help tune for improved battery perf

**Comment by xSmurf** [comment]
Sadly, they will probably never work due to kernel memory protection offered by grsecurity ([GRKERNSEC_KMEM](https://en.wikibooks.org/wiki/Grsecurity/Appendix/Grsecurity_and_PaX_Configuration_Options#Deny_reading.2Fwriting_to_.2Fdev.2Fkmem.2C_.2Fdev.2Fmem.2C_and_.2Fdev.2Fport)). This is not something we can or intend to fix since it derives from obvious security concerns.
