### ISSUE TITLE
Tor Browser should be included by default in the Live CD

### ISSUE THREAD

**Issue by lolscreen** [subgraph/subgraph-os-issues#213]
In the current version clicking on the Tor Browser launches the Tor Browser Launched which downloads the Tor Browser and installs it from scratch. It should be included by default from the start.

**Comment by xSmurf** [comment]
This won't work for a number of reasons.

a) we cannot predict the user's language and Tor Browser doesn't bundle all the translations
b) at this point we don't release images at a steady rate and it's likely the bundled version would be outdated quickly.

We've already discussed this internally and decided against it due to the above. Closing this.
