### ISSUE TITLE
Cannot install Chrome extensions

### ISSUE THREAD

**Issue by csoghoian** [subgraph/subgraph-os-issues#214]
Added chromium support to Subgraph, following the instructions [here](https://subgraph.com/sgos/documentation/clearnet-chromium/), then tried to install uBlock Origin.

Got an error telling me that extensions couldn't be installed. Hmm.
I removed the incognito command line flag in the chromium.json file. That didn't fix it.

Poked around a bit online, and it seems as though the Debian Chromium maintainers recently added some extremely unpopular features that, by default, both disable the installation of extensions and the ability for existing extensions to update. Folks on the [bug tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852398) aren't happy.

I tried adding --enable-remote-extensions to the .json file, as was suggested in the bug tracker, but that didn't help things.

Being able to use Chromium over the Tor browser is a huge step. Thank you for everything you've done on that. But for Subgraph to be an OS that I can use, and not just a fun weekend tinkering project, I need to be able to install an ad blocker, password manager, and other basic browser extensions.

If the Debian Chromium maintainer doesn't like extensions, perhaps it might make more sense to just use Google Chrome instead? Presumably, we'd get security updates faster then too.

**Comment by dma** [comment]
Just got Google Chrome stable working in Oz, it runs fine out of the box. You have to do a few extra steps, we'll try to make that easier. I'll post them shortly.

**Comment by dma** [comment]
In case you wanted more weekend hacking.. 

(fyi to any readers of this comment, this is an ugly hack)

Here's a profile for chrome stable from the Google deb repository. Couple of manual steps to use it, and it isn't guaranteed to survive a Chrome update, we may need to slightly modify Oz to support packages distributed and installed like this.

Profile: https://github.com/subgraph/subgraph-oz-profiles/commit/d7f663c20b8f9df3beed11bac7df2b625a7d15bf

Steps:

0) Grab the profile, copy it into /var/lib/oz/cells.d/

`$ sudo cp google-chrome-stable.json /var/lib/oz/cells.d/google-chrome-stable.json`

1) Install Google signing key:
`$ wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -`

2) Install google package repo:

`
$ sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
`

3) Update (but don't upgrade - we need to bump the version of the oz-daemon package you installed to test chromium in oz, otherwise it will get clobbered by a regression):

`$ sudo apt-get update`

4) Install google-chrome-stable:

`$ sudo apt-get install google-chrome-stable`

5) append the following entry to /etc/paxrat/paxrat.conf:
```

  "/opt/google/chrome/chrome": {
    "flags": "m"
  }

```
5a) Then run paxrat: 

`$ sudo paxrat`

6) You need to next do some surgery on the symbolic links /usr/bin/

Remove the symlink:

`$ sudo rm /usr/bin/google-chrome-stable`

Add new one:
```

$ cd /usr/bin/
$ sudo ln -s /usr/bin/oz google-chrome-stable

```
You also need to add a symlink in /usr/bin-oz/:
```

$ cd /usr/bin-oz/
$ ln -s /opt/google/chrome/google-chrome-stable google-chrome-stable

```
7) Send a HUP to the oz-daemon process OR restart it (close your apps first)

`$ sudo systemctl restart oz-daemon`

8) Click on the Chrome application icon to start it, or type google-chrome-stable at the command-line 
(I'll provide instructions next to make it just 'chrome' -- wanted to minimize steps)

Quite a few steps here, as you can see. We need to think about and make some small improvements in Oz to make this easier.

**Comment by xSmurf** [comment]
That's hmmm one option... But I, for one, recommend against using Chrome instead of Chromium as it ships with a number of blobs and has NaCl enabled.

If you would like to revert to the old, less safe, behavior: create a file under `/etc/chromium.d/allow_extensions` with the contents:

```
export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --enable-remote-extensions"
````

(This flag CANNOT be passed as an argument, and MUST be passed via the environment)

Alternatively, you can manually unpack the extension somewhere, say `/usr/local/share/chromium/extensions/extension_name` and add the specific extension by creating a file such as `/etc/chromium.d/extension_name` with the contents:

```
export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --load-extension=/usr/local/share/chromium/extensions/extension_name"
```


I'm not convinced this should be enabled by default as there are obvious reasons why this change was made and considering packaging µBlock, µMatrix, HTTPS Everywhere, and Signal instead... but that's obviously a lot of extra maintenance work for us. (As a side note, if someone knows how to work the version check google store API this would go a long way in helping me automate some of that).

As for security updates, as we migrate to more Chromium usage, I'd consider pinning it to unstable which, from past experience, receives updates rather quickly.

**Comment by dma** [comment]
Created oz issue 92 here for where we need to investigate & fix oz to support this application and others like it: https://github.com/subgraph/oz/issues/92.

**Comment by xSmurf** [comment]
(Bumped for slightly updated my previous comment)

**Comment by dma** [comment]
BTW, I confirm I could add uBlock Origin after I removed the incognito mode parameter from the profile.

**Comment by csoghoian** [comment]
Can confirm that installation of browser extensions from the Google Chrome app store worked after I added the /etc/chromium.d/allow_extensions file per xSmurf's suggestion above. Chromium is now usable.

Thanks!
