### ISSUE TITLE
Build scripts release When?

### ISSUE THREAD

**Issue by Pungee5** [subgraph/subgraph-os-issues#228]
Hi I've been interested and following your project for a long time. Big fan. I would like to roll my own image of Subgraph for trust reasons however the incomplete build script sources on git are an obstacle.

I know you are busy but I think its an urgent matter for security and for user freedom in general that the build process is publicly available. Can you please make it a priority and let me know a precise ETA for when this will happen?

**Comment by mckinney-subgraph** [comment]
I'm happy to document our staging environment and build process when I have time to do so. But our release engineering is not for the faint of heart. Not only are we constantly staging things when working on a release, we sometimes must also adapt to the availability of packages as well as their stability. We're making strides to improve this situation but that also takes time.

The main reason it is not all publicly documented at this point is because we don't want to provide technical support for people building potentially broken releases. There are numerous reasons that people could end up with a broken release. Some of these may be temporary. Some may just be from trying to tinker with the build process and configuration. Because of this, any documentation we release will be without warranty.

**Comment by Pungee5** [comment]
I understand you don't want to deal with more support requests but that's easily done if you post a big fat disclaimer with a "WIP no support provided" label.

However not releasing something because its unstable is not a good criteria, otherwise you'd be hard pressed to find more than five open source projects out in the open. Actually if you post them you may end up getting outside contributions to improve them too - one of the main benefits of open development.

**Comment by mckinney-subgraph** [comment]
The configuration for building the ISO is already public. It can be found here:
[https://github.com/subgraph/subgraph_desktop_stretch](https://github.com/subgraph/subgraph_desktop_stretch)

Anybody who is genuinely interested in building it can get pretty far just by running `lb build` using the `subgraph_desktop_stretch` config. `live-build` is doing all of the heavy lifting, there's no special scripts other than to make it easier for us to stage things with `live-build`.  

The missing pieces from our staging environment are the following:
- Some Makefiles to start `docker` processes such as `apt-cacher-ng` and the live build itself -- `apt-cacher-ng` and `live-build` can be run without `docker`, our assistance is not really required in this regard (note: we're currently evaluating moving to something other than `docker` due to some limitations)
- A few run-time variables such as the stuff to point `live-build` at `apt-cacher-ng` and set the kernel version, see the live-build manual for setting these up
- Kernel packages, which must be dropped in manually due to the way that live-build works, but those are available in our apt repo
- Other files we may be staging as part engineering a release, these would include packages and configurations we are testing (which end up on Github and in our apt repo for an actual release)
- Packages that may have (sometimes temporarily) fallen out of Stretch but are still dependencies in Subgraph OS
- Occasional patches to `live-build` itself (mostly a problem during the year in which `live-build` was orphaned, not so much of a requirement now)

The staging environment is not strictly required, it just allows us to run different scenarios and apply hot-fixes as needed. These pointers should be enough for you to go it alone with `live-build`. 

Since there is no avoiding getting your hands dirty with `live-build`, these are some of the problems that may occur (that are beyond our control at the moment):
- Debian repos get out sync, causing live-build to abort with no resolution until the repos get back in sync
- DPKG fails due to a non-zero return error in some random package
- Dependency problems due to Stretch package migrations
- General `live-build` bugs
- Upstream versions of `debian-installer` fail to build, meaning `live-build` aborts (sometimes you get an installer that builds successfully but is too buggy to actually install the OS)

> However not releasing something because its unstable is not a good criteria, otherwise you'd be hard  pressed to find more than five open source projects out in the open. Actually if you post them you may  end up getting outside contributions to improve them too - one of the main benefits of open development.

We did release the unstable part (the `live-build` config) a very long time ago. People have expressed interest in building their ISOs in the past but so far no takers as far as cloning our config and running `live-build` to see what happens. Yes, we haven't really encouraged this because we don't want to provide technical support for it. That doesn't stop anybody with `live-build` familiarity or a willingness to learn from attempting to build an ISO. There should now be enough here to fill in the blanks for anybody who wants to try. 

There's no magic at this phase -- just many iterations of building and breaking things until you get it right. The major improvements we will make in regards to stability require us to build out more of our infrastructure and removing other variables that otherwise cause things to break. That is an ongoing but slow process. Once that's all in place, it will just be easier for people to build their own ISOs due to the fact that will be easier for **us** to build them.

**Comment by mckinney-subgraph** [comment]
We cleaned up some cruft from our staging environment and migrated it into the live-build config. We did some tests and the vanilla config *should* work now with straight-up live-build from stretch. Again, no warranty.

Closing this issue, please visit https://github.com/subgraph/subgraph_desktop_stretch for build instructions.
