### ISSUE TITLE
Add vlc

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#24]
It would be useful to have a containerized vlc by default on sgos install.

**Comment by dma** [comment]
Note to include the recommends with vlc.

**Comment by ioerror** [comment]
These would be nice:

```
vlc-plugin-fluidsynth
vlc-plugin-jack
vlc-plugin-notify
vlc-plugin-samba
vlc-plugin-sdl
vlc-plugin-svg
vlc-plugin-zvbi
vlc-plugin-notify
```

Ideally libdvdnav and libdvd-pkg should be included so we can watch "Encrypted" DVDs.

**Comment by mckinney-subgraph** [comment]
Added everything but the following:
- vlc-plugin-samba (Samba client functionality possibly a 'can-of-worms', deferring or possibly permanently keeping it as an install option via apt-get but not making it a default)
- libdvdnav (not in Stretch currently, deferring)
- libdvd-pkg (needs to be looked at further since it "automates the process of downloading source files, compiling them, and installing the binary packages", still apt-gettable)

See:
https://github.com/subgraph/subgraph_desktop_stretch/commit/50d8fe1bc9534fb04bb2d1525cd4a471c015b059

**Comment by xSmurf** [comment]
Are we sure we really need `vlc-plugin-jack`? I don't think we'll be adding JACK support anytime soon.

**Comment by ioerror** [comment]
No, we don't need it.

**Comment by mckinney-subgraph** [comment]
Closing this issue as the core stuff and plug-ins have been added and vlc has been sandboxed. `apt-get install` can address any other missing parts.
