### ISSUE TITLE
Dev status

### ISSUE THREAD

**Issue by cryptono** [subgraph/subgraph-os-issues#263]
Last version is from 2016 - is there still active development? When is the next release expected?

**Comment by ghost** [comment]
They are still actively making changes but they do much of their work it seems behind the scenes.

I'm hoping someday in the near future they might launch a project website, forums and contributor documentation and open things up like a oss project.

**Comment by ghost** [comment]
@dma @xSmurf But yes it would be great if there was some sort of roadmap or predictable release timelines even if you guys decided to delay releases since there is not much communication to the users and community.

Like when are all these features around bridges and new menu settings coming? You talk about going back to unstable from stretch when will that happen?

**Comment by dma** [comment]
Active development, lots of major things happening. ISO release sometime soon, just delayed a bit on that for a couple of reasons + busy with consulting projects.

**Comment by cryptono** [comment]
Thanks @dma, glad to hear that!
