### ISSUE TITLE
Tor Bootstrap takes five minutes

### ISSUE THREAD

**Issue by ghost** [subgraph/subgraph-os-issues#266]
I'm not sure what other users experience but on two separate pieces of hardware running Subgraph if I tail the syslog it takes 5 minutes on average for a tor bootstrap.

Anyway Subgraph might consider building its own tor package from upstream instead of relying on Debian's lagging package? Ubuntu as a base for Subgraph would address this issue and also result in fresher packages for all the things (Wifi, firmware etc)

**Comment by xSmurf** [comment]
Debian Tor packages are maintained by the same person as the official Tor project repo and are nearly always in-sync with testing. Since we are currently on stable (since the stretch release a couple months ago) there is a short lag, but this will be gone when we are tracking testing again. Long Tor bootstrap are expected on first boot (ie after installing or in live mode) and don't have anything to do with the installed version but with the inherent way Tor works.
