### ISSUE TITLE
Gnome Desktop lag and performance issues

### ISSUE THREAD

**Issue by thiscantbeserious** [subgraph/subgraph-os-issues#322]
... or at least as an Option with an Tor applet predelivered?

I was pretty let down with the initial performance of Subgraph OS and it was seemingly only related to Gnome (Asus UX305UA-FC001D Intel Core i5 6200U, Intel HD Graphics 520, 8 GB Ram and an 256 GB SSD).

That said it was not related to any performance bottlenecks (maybe the GFX driver if anything) but what it seems like non-optimized UI animations (keep in mind fully up-to-date system with the latest Intel driver). Microlags everywhere, especially when I had a few applications open for example Chromium-Clearnet or when I was using the Launcher.

Budgie on the other hand with the Gnome theme looks almost exactly the same but is so much more smoother then Gnome itself. I have yet to encounter any slowdowns. The only thing that I'm missing is the Tor applet. I wouldn't dare to think twice of ever going to back to Gnome. 

No hiccups, no microlags, no nothing.

I would really recommend you to look into it if you haven't done so already. I'm all for keeping a sleek system without to much clutter and maximum compability but shouldn't come with the price of sluggy UX.  Budgie is very well worth it in my opinion.

Just a humble opinion / suggestion! :)

**Comment by brl** [comment]
Maybe turning off animations with the tweak tool will help?  I do wonder if any of the problems you're experiencing are related to our use of xpra for display isolation in the sandboxes, which we have plans to replace soon with a new solution.  Also,  we will be moving from X to Wayland which should at least have a different set of problems.  

Did you install Budgie desktop inside Subgraph OS or are you comparing an entirely different distribution?  Both Budgie and Gnome use Mutter as the underlying compositor so it's not really possible that Budgie can perform fundamentally better. I myself use an older model of the same Zenbook (UX305) with a similar but slightly less powerful GPU (HD 515) and Gnome works fine for me.  It could be that I'm just less sensitive to lagging animations, and perhaps have lower expectations for desktop Linux, but I've never noticed a problem.

Budgie looks very nice and a lot of people seem to like it but we're very deeply invested in Gnome at this point.  We understand the Gnome codebase and ecosystem, and we're in the process of making substantial changes to various Gnome desktop components.  Budgie on the other hand is currently written in an abandoned programming language (Vala) and is also currently being rewritten in Qt/C++.  Even though Budgie is probably a really great experience for some users, it's not a project which is convenient for us to maintain a set of changes against.  However since Budgie is built on Mutter, if we ever were to decide to switch to a different desktop environment, we'd probably take a look at Budgie first.  But for now, we're mostly happy with Gnome.

I would suggest trying a Fedora 27 live boot to confirm that your beef really is with the Gnome desktop itself rather than something that we've done which makes Gnome run suboptimally.

**Comment by brl** [comment]
I'm going to leave this issue open for other users to report similar problems, as I see people mentioning issues with Gnome desktop animation lag frequently in the Linux desktop community.  

I found this [i915 driver bug report](https://bugs.freedesktop.org/show_bug.cgi?id=102199) today which may explain the cause of lag specifically on Kabylake processors, but as the original poster of this issue reported a Skylake processor, this probably doesn't apply to them.

**Comment by burdges** [comment]
As an aside, I noticed the gnome-tweak-tool has no effect on say dynamic workspaces, presumably because `gsettings set org.gnome.shell.overrides dynamic-workspaces true` has no effect.  Instead, you need `gsettings set org.gnome.shell.mutter dynamic-workspaces true`.  If tweak tool has no effect, then use it's `gsettings describe` to figure out where else to try.

**Comment by leo-petrucci** [comment]
I am also encountering these issues on Ubuntu with Gnome installed. There's a whole thread over at reddit of people experiencing the same problem and it doesn't look like a problem related to hardware.
https://www.reddit.com/r/linux/comments/8tv449/anyone_else_notice_the_lag_of_gnome_shell_app/

**Comment by thiscantbeserious** [comment]
Closing since this is a ghost-town now :hamburger:
