### ISSUE TITLE
Paxrat path for TBB doesn't care for localization

### ISSUE THREAD

**Issue by xSmurf** [subgraph/subgraph-os-issues#58]
If a user selects a different locale, the path for TBB in the inotify paxrat rule does not work as `tor-browser_en-US` becomes something like `tor-browser_de-DE`.

**Comment by xSmurf** [comment]
Currently marked as "wontfix" as this should be resolved once TBBL is migrated to an actual package.

**Comment by mckinney-subgraph** [comment]
Since we are still in the process of deciding what to do with the Tor Browser, I have addressed this issue by adding the localized paths for all supported localizations to the `paxrat_tbl.conf` file. There are not that many localizations in the end and they are added infrequently. 

This was the cheapest and most robust option over the added complexity of implementing globbing + better recursion for the inotify watches or trying to pre-compute the locale path at the time the inotify watches are created (which creates an issue if the locale is changed after the watch is created). 

The updated settings are available in the paxrat 1.19 package.
