### ISSUE TITLE
text truncated on install screen

### ISSUE THREAD

**Issue by hnapel** [subgraph/subgraph-os-issues#79]
Using Dutch as install language I get to the screen 'Schijven Indelen' (formatting disks) and it is wiping the disk with random data, however the text explaining the process is truncated below the progress bar.
![subgraph_issue_001](https://cloud.githubusercontent.com/assets/17120719/12882486/36f3f14a-ce52-11e5-9d49-c8070ede1b4d.jpg)

**Comment by hnapel** [comment]
Subsequent install screens may show the same behaviour if the text is long.

**Comment by mckinney-subgraph** [comment]
@hnapel I'm sorry to hear this. :( Unfortunately, this is an issue in the debian-installer that we use out-of-the-box. We plan to migrate to another installer in the mid- to long-term. 

However, it is very actively maintained so I suggest you file your bug here:
https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=debian-installer
