### ISSUE TITLE
data leak / fingerprinting: subgraph connect to clearnet repo (f33dtime) during install.

### ISSUE THREAD

**Issue by zqir** [subgraph/subgraph-os-issues#82]
When installing, anaconda(?) attempts to update repositories and connects to the f33dtime.com repo in the clear.

Any nation state actor can now identify subgraph beta users by monitoring connections to this side, or monitoring for dns requests for this domain.

(The installed also connects to ntp servers and the other default repository but unless attackers attempt to identify specific flavors of os using package updates it's not a problem)

Solutions:
1) Configure installer to skip updates.

2) Disable all networking during installation for now. Have updates downloaded on firstboot once tor is loaded.

3) Kill the f33dtime server and/or
a) Set up a quick and dirty .onion as a repo. (Use single-hop mode in the settings for a speed boost since you don't care about hiding the location of the server.) 
b) Use a public, commonly used, ssl protected server as a front for the repo. (Can you run a repo on github? Cloudflare? google apps server? How do you know if they're compromised or not?)
c) Set up a canonical ppa (Do they even have https?)

It's too late for the testers using the current pre-alpha. Best thing you can do now is post a warning on the front page and pull the iso from the server before the link spreads too far. (I got my copy from twitter)

Ps: Are those ports on f33dtime supposed to be open?

**Comment by zqir** [comment]
Ps: Just to clarify: "When installing, anaconda(?) attempts to update repositories and connects to the f33dtime.com repo in the clear."
The installed connects directly WITHOUT going via tor.

**Comment by dma** [comment]
Hi zqir, thanks for this very good issue report. BTW, since you found the download link on Twitter, have you read the release notes here? https://support.subgraph.com/private/sgos/pre-alpha/ 

There are explicit warnings about the state of Subgraph OS in general. It is very clearly and prominently stated that it is not fit for serious use. We made the ISO available exclusively for testing, this is one reason why we have asked users to drop into our IRC channel to get the download link.

We're aware of most of these issues.  The installer is the last major component that is not yet complete. We will almost ditch the Debian installer entirely and either write our own or heavily adapt another. 

Disabling network is one option, as is disabling updates at install time. We've talked about doing both. Using a very public server is an interesting idea worth discussing.

f33dtime.com is very, very temporary and will be discontinued and taken down entirely soon.

**Comment by dma** [comment]
I'll add a detail to the release notes clarifying that there's no egress over Tor while the installer is running, and that we are still using the vanilla Debian installer.

**Comment by zqir** [comment]
Thanks.
I'm testing the sandbox features right now. Really good stuff so far.

Regarding the irc channel. I think oftc are still blocking tor users. (Whonix support irc have the same problem and are looking to move to another network or even maybe another protocol.)

**Comment by botherder** [comment]
OFTC doesn't block Tor users as a whole. It blocks some exit nodes if they produce malicious traffic or a connection threshold is passed. If you change identity a couple of times you'll eventually get on it. It's annoying tho, I agree.

**Comment by dma** [comment]
@zqir if you haven't already, read this Oz sandbox walkthrough: https://github.com/subgraph/oz/wiki/Oz-Technical-Details. Take note that we are replacing Xpra with Wayland sometime in the mid-term future. We already have Wayland working in SGOS and in Oz for some apps.

**Comment by dma** [comment]
I believe that @mckinney-subgraph has fixed these issues. There is no more network during install and the repo (now devrepo.subgraph.com) has been configured for tor+https. Closing.
